turbo_chat/config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages, only: %i[new create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

turbo_chat/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

turbo_chat/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

turbo_chat/app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
end

turbo_chat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

turbo_chat/app/controllers/messages_controller.rb
class  MessagesController < ApplicationController
  before_action :set_room

  def new
    @message = @room.messages.new
  end

  def create
    @messages = @room.messages.create!(message_params)

    respond_to do |format|
        format.html { redirect_to @room }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params.require(:room_id))    
    end
    
    def message_params
      params.require(:message).permit(:content)
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.expect(room: [ :name ])
    end
end

turbo_chat/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_path, notice: "Room was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params.require(:id))
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.expect(room: [ :name ])
    end
end

turbo_chat/app/helpers/application_helper.rb
module ApplicationHelper
end

turbo_chat/app/helpers/rooms_helper.rb
module RoomsHelper
end

turbo_chat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Turbo Chat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Turbo Chat">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
    <%= turbo_include_tags %> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

turbo_chat/app/views/messages/_message.html.erb
<p id="<%= dom_id message %>">
    <%= message.created_at.to_formatted_s(:short) %>: <%= message.content %>
</p>

turbo_chat/app/views/messages/new.html.erb
<div class="ui-card">
    <h1> New Message </h1>

    <%= turbo_frame_tag "new_message", target: "_top" do %>
        <%= form_with(model: [ @message.room, @message ]) do |form| %>
            <div class="field">
                <%= form.text_field :content %>
                <%= form.submit "Send" %>
            </div>
        <% end %>
    <% end %>

    <%= link_to 'Back', @message.room %>
</div>

turbo_chat/app/views/rooms/_form.html.erb
<%= form_with(model: @room) do |form| %>
  
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="margin: 10px; align-items: center;">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  
<% end %>

turbo_chat/app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <div>
    <strong>Name:</strong>
    <%= room.name %>
  </div>

</div>

turbo_chat/app/views/rooms/edit.html.erb
<div class="ui-card">
  <% content_for :title, "Editing room" %>

  <h1>editing room</h1>

  <%= turbo_frame_tag "room" do %>
    <%= render 'form', room: @room %>
  <% end %>

  <br>

  <div style="margin-top: 10px;">
    <%= link_to "show this room", @room %> |
    <%= link_to "back to rooms", rooms_path %>
  </div>
</div>

turbo_chat/app/views/rooms/index.html.erb
<div class="ui-card">

  <% content_for :title, "Rooms" %>

  <h1>chat rooms</h1>

  <%= link_to "create new room", new_room_path %>

  <div id="rooms" class="room-section">
    <% @rooms.each do |room| %>
      <div style="margin: 5px;">
        <%= render room %>
        <p>
          <%= link_to "go to this room", room %>
        </p>
      </div>
    <% end %>
  </div>

</div>

turbo_chat/app/views/rooms/new.html.erb
<div class="ui-card">

  <% content_for :title, "New room" %>

  <h1>new room</h1>

  <%= render "form", room: @room %>

  <br>

  <div style="margin-top: 10px;">
    <%= link_to "back to rooms", rooms_path %>
  </div>
</div>

turbo_chat/app/views/rooms/show.html.erb
<div class="ui-card">

  <%= turbo_frame_tag "room" do %>
    <p>
      <strong>Name:</strong>
      <%= @room.name %>
    </p>

    <p>
      <%= link_to 'Edit', edit_room_path(@room) %> |
      <%= link_to 'Back', rooms_path, "data-turbo-frame": "_top"%>
    </p>
  <% end %>

  <div id="messages">
    <%= render @room.messages %>
  </div>

  <%= link_to "New Message", new_room_message_path(@room) %>
  <%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "_top" %>
</div>